platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'StudySwift' do
  pod 'LookinServer', :configurations => ['Debug']
# swift
end

# Extension 名字  在Targets里面可以查看名字
target 'MainExtension' do
  pod 'ObjectMapper'
  pod 'Moya'
  pod 'ObjectMapper'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
end
